### ISSUE TITLE
Cannot change position mode while a position is open

### ISSUE THREAD

**Issue by iZnogoude** [germangar/whook#10] opened 2024-05-20 08:12 UTC
Hello Germangar,

I have a new issue since I uptaded to the new release the main.py
Pair : ONDO, STX
leverage : 5
Position : short, isolated
Broker : BingX
Whook server : Ubuntu AWS, last release of your whook script
Log :

[2024/05/15][16:15:02]  
[2024/05/15][16:15:02]  ALERT: iznogoude31@gmail.com ONDOUSDT sell 195.84@ x5
[2024/05/15][16:15:02] ----------------------------
[2024/05/15][16:15:02]  
[2024/05/15][16:15:02]  ALERT: iznogoude31@gmail.com STXUSDT sell 66@ x5
[2024/05/15][16:15:02] ----------------------------
[2024/05/15][16:15:07]  * Order successful: ONDO/USDT:USDT sell 195.84 5x at price 0.8166 id 1790777936443559936
[2024/05/15][16:15:09]  * Order successful: STX/USDT:USDT sell 66.0 5x at price 2.1012 id 1790777949856944128
[2024/05/15][16:45:04]  
[2024/05/15][16:45:04]  ALERT: iznogoude31@gmail.com ONDOUSDT sell 15.61@ x5
[2024/05/15][16:45:04] ----------------------------
[2024/05/15][16:45:05]  * W: Cannot change position mode while a position is open
[2024/05/15][16:45:06]  * Order successful: ONDO/USDT:USDT sell 15.61 5x at price 0.8245 id 1790785485511282688
[2024/05/15][17:15:01]  
[2024/05/15][17:15:01]  ALERT: iznogoude31@gmail.com ONDOUSDT sell 14.2@ x5
[2024/05/15][17:15:01] ----------------------------
[2024/05/15][17:15:03]  * W: Cannot change position mode while a position is open
[2024/05/15][17:15:05]  * Order successful: ONDO/USDT:USDT sell 14.2 5x at price 0.8376 id 1790793029382262784
[2024/05/15][19:30:06]  
[2024/05/15][19:30:06]  ALERT: iznogoude31@gmail.com STXUSDT sell 6@ x5
[2024/05/15][19:30:06] ----------------------------
[2024/05/15][19:30:07]  * W: Cannot change position mode while a position is open
[2024/05/15][19:30:08]  * Order successful: STX/USDT:USDT sell 6.0 5x at price 2.1313 id 1790827017660485632
[2024/05/15][20:45:02]  
[2024/05/15][20:45:02]  ALERT: iznogoude31@gmail.com STXUSDT sell 5@ x5
[2024/05/15][20:45:02] ----------------------------
[2024/05/15][20:45:03]  * W: Cannot change position mode while a position is open
[2024/05/15][20:45:04]  * Order successful: STX/USDT:USDT sell 5.0 5x at price 2.1808 id 1790845874622124032
[2024/05/15][21:15:00]  
[2024/05/15][21:15:00]  ALERT: iznogoude31@gmail.com ONDOUSDT buy 14.2@ x5
[2024/05/15][21:15:00] ----------------------------
[2024/05/15][21:15:01]  * W: Cannot change position mode while a position is open
[2024/05/15][21:15:03]  * Order successful: ONDO/USDT:USDT buy 14.2 5x at price 0.828 id 1790853417855569920
[2024/05/16][00:45:01]  
[2024/05/16][00:45:01]  ALERT: iznogoude31@gmail.com STXUSDT buy 5@ x5
[2024/05/16][00:45:01] ----------------------------
[2024/05/16][00:45:01]  * W: Cannot change position mode while a position is open
[2024/05/16][00:45:02]  * Order successful: STX/USDT:USDT buy 5.0 5x at price 2.1528 id 1790906265645568000

My friend is gdumgdum, mayby his fork is up to date.
I'm pretty shure that he hasn't modified the by or sell function.

Thanks for your support.

**Comment by iZnogoude** [comment] 2024-05-20 14:57
It you look the log, on the first lines it creates correctly the positions in the exchange of my broker => short.

```
[2024/05/15][16:15:02] ALERT: [iznogoude31@gmail.com](mailto:iznogoude31@gmail.com) ONDOUSDT sell 195.84@ x5
[2024/05/15][16:15:02] ----------------------------
[2024/05/15][16:15:02]
[2024/05/15][16:15:02] ALERT: [iznogoude31@gmail.com](mailto:iznogoude31@gmail.com) STXUSDT sell 66@ x5
[2024/05/15][16:15:02] ----------------------------
[2024/05/15][16:15:07] * Order successful: ONDO/USDT:USDT sell 195.84 5x at price 0.8166 id 1790777936443559936
[2024/05/15][16:15:09] * Order successful: STX/USDT:USDT sell 66.0 5x at price 2.1012 id 1790777949856944128
```

The issue happens when the bot send a new alert to buy. I was not in front of it when the alerts happens, but when the alerts creates some news positions => long.
So at the end I had 4 positions, 2 short and 2 long.
```

[2024/05/15][21:15:00] ALERT: [iznogoude31@gmail.com](mailto:iznogoude31@gmail.com) ONDOUSDT buy 14.2@ x5
[2024/05/15][21:15:00] ----------------------------
[2024/05/15][21:15:01] * W: Cannot change position mode while a position is open
[2024/05/15][21:15:03] * Order successful: ONDO/USDT:USDT buy 14.2 5x at price 0.828 id 1790853417855569920
[2024/05/16][00:45:01]
[2024/05/16][00:45:01] ALERT: [iznogoude31@gmail.com](mailto:iznogoude31@gmail.com) STXUSDT buy 5@ x5
[2024/05/16][00:45:01] ----------------------------
[2024/05/16][00:45:01] * W: Cannot change position mode while a position is open
[2024/05/16][00:45:02] * Order successful: STX/USDT:USDT buy 5.0 5x at price 2.1528 id 1790906265645568000
```

The thing that is incomprehensible for me is that even on sell the message in the log is the same. It shouldn't be because the position are short.
```

[2024/05/15][16:45:04] ALERT: [iznogoude31@gmail.com](mailto:iznogoude31@gmail.com) ONDOUSDT sell 15.61@ x5
[2024/05/15][16:45:04] ----------------------------
[2024/05/15][16:45:05] * W: Cannot change position mode while a position is open
[2024/05/15][16:45:06] * Order successful: ONDO/USDT:USDT sell 15.61 5x at price 0.8245 id 1790785485511282688
[2024/05/15][17:15:01]
[2024/05/15][17:15:01] ALERT: [iznogoude31@gmail.com](mailto:iznogoude31@gmail.com) ONDOUSDT sell 14.2@ x5
[2024/05/15][17:15:01] ----------------------------
[2024/05/15][17:15:03] * W: Cannot change position mode while a position is open
[2024/05/15][17:15:05] * Order successful: ONDO/USDT:USDT sell 14.2 5x at price 0.8376 id 1790793029382262784
```

Maybe I should try to reproduce the issue and screen what happens exactly.
Don't hesitate if you need more input (I'm not an expert).

**Comment by germangar** [comment] 2024-05-20 15:02
Yes the error is saying it can't set the position mode to oneway when a position is opened. It shouldn't be trying to do it. It should already know it's in isolated and not even try.

You can get this warning if you had a position opened manually in hedged before you start the script, but if there was none or if it was already in oneway it should be saying anything.

**Comment by germangar** [comment] 2024-05-28 00:52
I'm unable to reproduce this one. The warning is not showing up:

```
 * Listening
 * Serving Flask app 'main'   
 * Debug mode: off
02:40:11 [bingx/bingx]  
02:40:11 [bingx/bingx]  ALERT: ATOMUSDT bingx pos -3$ x20
02:40:11 [bingx/bingx] ----------------------------      
02:40:14 [bingx/bingx]  * Order successful: ATOM/USDT:USDT sell 6.9 20x at price 8.686 id 1795253714899124224
------------------------------
  1 positions found.
  ATOM/USDT:USDT * isolated:20x * short * 6.9 * 2.9974[$] * 0.01[$] * 0.32%
------------------------------
02:40:38 [bingx/bingx]  
02:40:38 [bingx/bingx]  ALERT: ATOMUSDT bingx pos -6$ x20
02:40:38 [bingx/bingx] ----------------------------      
02:40:41 [bingx/bingx]  * Order successful: ATOM/USDT:USDT sell 6.92 20x at price 8.682 id 1795253824613728256
------------------------------
  1 positions found.
  ATOM/USDT:USDT * isolated:20x * short * 13.82 * 5.9996[$] * 0.02[$] * 0.30%
------------------------------
02:42:11 [bingx/bingx]  
02:42:11 [bingx/bingx]  ALERT: ATOMUSDT bingx sell 3$ x20
02:42:11 [bingx/bingx] ----------------------------      
02:42:13 [bingx/bingx]  * Order successful: ATOM/USDT:USDT sell 6.9 20x at price 8.687 id 1795254211156590592
------------------------------
  1 positions found.
  ATOM/USDT:USDT * isolated:20x * short * 20.72 * 8.9966[$] * -0.07[$] * -0.73%
------------------------------
02:44:05 [bingx/bingx]  
02:44:05 [bingx/bingx]  ALERT: ATOMUSDT bingx buy 3$ x20
02:44:05 [bingx/bingx] ----------------------------
02:44:07 [bingx/bingx]  * Order successful: ATOM/USDT:USDT buy 6.91 20x at price 8.678 id 1795254692478140416
------------------------------
  1 positions found.
  ATOM/USDT:USDT * isolated:20x * short * 13.81 * 5.9963[$] * 0.09[$] * 1.42%
------------------------------
02:48:51 [bingx/bingx]  
02:48:51 [bingx/bingx]  ALERT: ATOMUSDT bingx buy 3$ x20
02:48:51 [bingx/bingx] ----------------------------     
02:48:53 [bingx/bingx]  * Order successful: ATOM/USDT:USDT buy 6.92 20x at price 8.66 id 1795255891818397696
------------------------------
  1 positions found.
  ATOM/USDT:USDT * isolated:20x * short * 6.89 * 2.9916[$] * 0.17[$] * 5.61%
------------------------------
```

**Comment by iZnogoude** [comment] 2024-06-03 15:29
Hello there !
I had the issue again, but I have noticed something.
first, I start my bot when the margin mode was set up to crossed in my exange interface and I din't had the issue because, I think, the whook margin mode was set up to crossed aswell.

Then, I close this position and restart the bot but the difference is that on my exange interface it's set up on limited now. And I had the message again. So maby it's an issue with bingx with one the latest release of the whook.

I'm struggling a little bit with the update of ccxt, but I will let you know when done.

**Comment by iZnogoude** [comment] 2024-06-04 05:28
I had the issue again even if the martgin mode is the same on the exange interface :+1: 

The first order is ok
The two buy orders hapens next had the correct behavior on the exange.
The the five sell order has created a new position "short" instead selling on my long position.

So in result I have a long an a short
![image](https://github.com/germangar/whook/assets/166412344/29c371bf-f08a-4b4a-9cf0-7b9ca9b19adf)

This is the order history (there is 2 hours difference of my whook server)
![image](https://github.com/germangar/whook/assets/166412344/103a4f87-e8f8-4ebd-b334-2c9b4986ab61)
he should close long instead of opening short


```
[2024/06/03][15:15:01]  ALERT: iznogoude31@gmail.com ONDO/USDT:USDT buy 158.4@ x4
[2024/06/03][15:15:01] ----------------------------
[2024/06/03][15:15:03]  * Order successful: ONDO/USDT:USDT buy 158.4 4x at price 1.377 id 1797648193619709953
[2024/06/03][16:45:00]  
[2024/06/03][16:45:00]  ALERT: iznogoude31@gmail.com ONDO/USDT:USDT buy 10.52@ x4
[2024/06/03][16:45:00] ----------------------------
[2024/06/03][16:45:01]  * W: Cannot change position mode while a position is open
[2024/06/03][16:45:03]  * Order successful: ONDO/USDT:USDT buy 10.52 4x at price 1.3713 id 1797670844341899264
[2024/06/03][19:30:03]  
[2024/06/03][19:30:03]  ALERT: iznogoude31@gmail.com ONDO/USDT:USDT buy 10.39@ x4
[2024/06/03][19:30:03] ----------------------------
[2024/06/03][19:30:05]  * W: Cannot change position mode while a position is open
[2024/06/03][19:30:06]  * Order successful: ONDO/USDT:USDT buy 10.39 4x at price 1.3548 id 1797712378013634560
[2024/06/04][00:15:00]  
[2024/06/04][00:15:00]  ALERT: iznogoude31@gmail.com ONDO/USDT:USDT sell 10.39@ x4
[2024/06/04][00:15:00] ----------------------------
[2024/06/04][00:15:01]  * W: Cannot change position mode while a position is open
[2024/06/04][00:15:02]  * Order successful: ONDO/USDT:USDT sell 10.39 4x at price 1.3792 id 1797784083792875520
[2024/06/04][00:30:01]  
[2024/06/04][00:30:01]  ALERT: iznogoude31@gmail.com ONDO/USDT:USDT sell 10.52@ x4
[2024/06/04][00:30:01] ----------------------------
[2024/06/04][00:30:03]  * W: Cannot change position mode while a position is open
[2024/06/04][00:30:04]  * Order successful: ONDO/USDT:USDT sell 10.52 4x at price 1.3859 id 1797787867529039872
[2024/06/04][01:00:07]  
[2024/06/04][01:00:07]  ALERT: iznogoude31@gmail.com ONDO/USDT:USDT sell 10.56@ x4
[2024/06/04][01:00:07] ----------------------------
[2024/06/04][01:00:07]  * W: Cannot change position mode while a position is open
[2024/06/04][01:00:08]  * Order successful: ONDO/USDT:USDT sell 10.56 4x at price 1.4014 id 1797795435961864192
[2024/06/04][01:15:00]  
[2024/06/04][01:15:00]  ALERT: iznogoude31@gmail.com ONDO/USDT:USDT sell 10.56@ x4
[2024/06/04][01:15:00] ----------------------------
[2024/06/04][01:15:00]  * W: Cannot change position mode while a position is open
[2024/06/04][01:15:02]  * Order successful: ONDO/USDT:USDT sell 10.56 4x at price 1.4198 id 1797799182863650816
[2024/06/04][01:45:00]  
[2024/06/04][01:45:00]  ALERT: iznogoude31@gmail.com ONDO/USDT:USDT sell 10.56@ x4
[2024/06/04][01:45:00] ----------------------------
[2024/06/04][01:45:01]  * W: Cannot change position mode while a position is open
[2024/06/04][01:45:02]  * Order successful: ONDO/USDT:USDT sell 10.56 4x at price 1.432 id 1797806735655915520
```

**Comment by iZnogoude** [comment] 2024-06-04 07:28
Last update!
A friend of mine tell me to check is my exange was not set up to hedge mode.... and he was right. But I never change to hedge mode....So, I will change to one-dide mode and check again.
Maby there is something in the main.py that's tell the exange to switch to hedge mode? That would be curious.

**Comment by germangar** [comment] 2024-06-04 18:07
Hmm... whook should change it to oneway mode as long as a position wasn't previously open. Something is misbehaving, but I can't figure out what.

**Comment by germangar** [comment] 2024-06-08 18:48
Ok. Having no position open in any symbol I tested it. I set the website to this:

![image](https://github.com/germangar/whook/assets/83035204/4b0dc68d-a257-4c7b-9d5c-8826f51732ae)

And I place the order:
```
20:40:22 [bingx/bingx]  
20:40:22 [bingx/bingx]  ALERT: bingx BTCUSDT pos -3$ x30
20:40:22 [bingx/bingx] ----------------------------     
20:40:25 [bingx/bingx]  * Order successful: BTC/USDT:USDT sell 0.0012 30x at price 69454.2 id 1799511821602996224
------------------------------
  1 positions found.
  BTC/USDT:USDT * isolated:30x * short * 0.0012 * 2.7782[$] * 0.00[$] * 0.02%
------------------------------
```
This hasn't changed in the website. It's saying the same
![image](https://github.com/germangar/whook/assets/83035204/d910af75-7be4-4337-9031-b549c1568eb6)

But on the position it's looking correct:
![image](https://github.com/germangar/whook/assets/83035204/0d92bc63-bd74-4ced-83e2-274eb0586b61)

So I added a second sell on top:
```
20:46:00 [bingx/bingx]  
20:46:00 [bingx/bingx]  ALERT: bingx BTCUSDT pos -4$ x30
20:46:00 [bingx/bingx] ----------------------------
20:46:02 [bingx/bingx]  * Order successful: BTC/USDT:USDT sell 0.0005 30x at price 69446.3 id 1799513234609487872
------------------------------
  1 positions found.
  BTC/USDT:USDT * isolated:30x * short * 0.0017 * 3.9356[$] * 0.01[$] * 0.25%
------------------------------
```
And it's still looking fine.

So I refreshed the website and it is now showing the correct position mode
![image](https://github.com/germangar/whook/assets/83035204/3367f5dc-eaf8-4323-8bda-619b752fe9c4)

Everything seems to be working correctly. I can't reproduce the problem.

**Comment by germangar** [comment] 2024-06-08 19:25
I'm thinking a possible reason for the issue is this:

Whook only refreshes the position information when making an order or every 5 minutes. If you close a position from the website whook may spend the next 4 or 5 minutes thinking the position still exists. So if you had a position in hedged, closed it and quickly made a new order Whook may still think it can't change position mode because it still has the information of the closed position.

The solution is to restart the script or to wait the 5 minutes.

**Comment by iZnogoude** [comment] 2024-06-11 07:49
I guess I think the issue was that I had a position opened on hedge mode when I start the bot. That's why I had the error message. I have to try without any opened positions.
I will keep you updated.

**Comment by germangar** [comment] 2024-06-11 10:24
What I do is to create a subaccount for the bots. That way I have the main account for my manual operations.

But Bingx has the creation of subaccounts temporary disabled, so no luck with this one.

**Closed** 2024-06-29 14:39 UTC
